name: Sync content with S3 Staging

on:
  workflow_dispatch:
  pull_request_target:
    types: [ closed ]
    branches: [ main ]

jobs:
  sync:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    uses: hellocoop/tools/.github/workflows/code-deploy-client.yml@main
    with:
      AWS_ACCOUNT: ${{ vars.HELLO_STAGING_AWS }} # set at org level 
      STACK: QuickstartStack
      BUILD_CMD: npm run build
      TARGET: main
      DOMAIN: quickstart.hello-staging.net # for version comparison      
      BUILD_DIR: ./S3